### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by electrum** [HubSpot/dependency-scope-maven-plugin#2]
What is the license for this project? Please add a LICENSE file or similar.

**Comment by jhaber** [comment]
Sorry about that, just added an Apache 2.0 license
https://github.com/HubSpot/dependency-scope-maven-plugin/blob/master/LICENSE

**Comment by jhaber** [comment]
Also cut a new release (0.9) with the license

**Comment by electrum** [comment]
Thanks!
